ACD:
  - "^([Ee]xecution [Ll]ayer [Mm]eeting.*|.*[Cc]onsensus.*[Cc]all.*\\d+.*|.*ACDC.*|.*ACDE.*|.*All Core Devs.*)"

Execution:
  - "^([Ee]xecution [Ll]ayer [Mm]eeting.*|.*EOF.*|.*EVMMAX.*|.*eth_simulate.*|.*eth_multicall.*|.*Portal.*|.*RPC.*|.*EVM.*|.*[Ss]tateless.*|All Core Devs - Execution.*|.*ACDE.*)"

Consensus:
  - "^(.*[Cc]onsensus.*[Cc]all.*\\d+.*|.*FOCIL.*|All Core Devs - Consensus.*|.*ACDC.*)"

Beam:
  - "^(.*[Bb]eam [Cc]all.*|.*[Bb]eam [Cc]hain.*)"

Breakout:
  - "^(.*[Bb]reakout.*|.*[Ii]mplementer.*|.*[Bb]reak-[Oo]ut.*|.*RPC.*|.*[Bb]reak [Oo]ut.*)"

Interop:
  - "^(.*[Ii]nterop.*|.*RollCall.*|.*[Rr]ollup.*)"

L2:
  - "^(L2.*|.*Roll[Cc]all.*|.*[Rr]ollup.*)"

Portal:
  - "^(Portal.*)"

DA:
  - "^(.*PeerDAS.*)"

ePBS:
  - "^(.*EIP-7732.*|.*[Ee]PBS.*)"

EOF:
  - "^(EOF Implementer.*)"

Stateless:
  - "^(.*[Ss]tateless.*)"

eth-multicall:
  - "^(.*eth_simulate.*|.*eth_multicall.*)"

Cryptography:
  - "^(.*EVMMAX.*)"

API:
  - "^(.*RPC.*)"

Gas:
  - "^(.*[Rr]esource [Pp]ricing.*)"

PeerDAS:
  - "^(.*PeerDAS.*)"

EVMMAX:
  - "^(.*EVMMAX.*)"

ILs:
  - "^(.*FOCIL.*|.*[Ii]nclusion [Ll]ist.*)"

RollCall:
  - "^(Roll[Cc]all.*)"
