# ethereum_vocab.yaml

clients:
  execution:
    - Geth
    - Nethermind
    - Besu
    - Erigon
    - Reth
  consensus:
    - Prysm
    - Lighthouse
    - Lodestar
    - Teku
    - Nimbus
    - Grandine

upgrades:
  past:
    - The Merge
    - Shanghai
    - Capella
    - Dencun
    - Pectra
    - Fusaka
  current:
    - Glamsterdam
  future:
    - Hegota

acronyms:
  - EIP: Ethereum Improvement Proposal
  - EOF: EVM Object Format
  - ePBS: enshrined Proposer-Builder Separation
  - PeerDAS: Peer Data Availability Sampling
  - FOCIL: Fork-Choice Inclusion Lists
  - SSZ: Simple Serialize
  - RLP: Recursive Length Prefix
  - MPT: Merkle Patricia Trie
  - MEV: Maximal Extractable Value
  - EL: Execution Layer
  - CL: Consensus Layer
  - PFI: Proposed for Inclusion
  - CFI: Considered for Inclusion
  - DFI: Declined for Inclusion
  - SFI: Scheduled for Inclusion
  - BPO: Blob Parameter Only

meetings:
  - ACD: All Core Devs
  - ACDE: All Core Devs Execution
  - ACDC: All Core Devs Consensus
  - ACDT: All Core Devs Testing

infrastructure:
  - MevBoost
  - CommitBoost
  - Flashbots
  - Kurtosis

orgs:
  - Ethereum Foundation (EF)
  - Flashbots
  - Lido
  - Consensys
  - Offchain Labs

technical_terms:
  - blob
  - beacon chain
  - validator
  - attestation
  - proposer
  - builder
  - relay
  - devnet
  - testnet
  - mainnet
  - precompile
  - opcode
  - gas limit
  - mempool

# Common transcription errors
error_patterns:
  - fossil: FOCIL
  - prism: Prysm
  - nevermind: Nethermind
  - bezo: Besu
  - bass suit: Besu
  - aragon: Erigon
  - wrath: Reth
  - light house: Lighthouse
  - load star: Lodestar
  - take you: Teku
  - grandee: Grandine
  - eep: EIP
  - e-i-p: EIP
  - peer das: PeerDAS
  - e-p-b-s: ePBS
  - e pbs: ePBS
  - s-s-z: SSZ
  - e-o-f: EOF
  - pectra: Pectra
  - few soccer: Fusaka
  - glam sterdam: Glamsterdam
  - golass: Gloas